// Regression: cells with a formula but no cached value must render the
// COMPUTED result, not the formula text. Fixture is generated by ExcelJS
// without calc() — first row has =A2+B2 where A2=10, B2=3 → expect 13.
import { test, expect } from './_setup.mjs';

const FIXTURE = 'formulas-no-cache.xlsx';

test('Formula calc: =A2+B2 renders as computed value (not formula text)', async ({ page, fixtureIds, cspViolations }) => {
  const info = fixtureIds[FIXTURE];
  expect(info, `Fixture ${FIXTURE} not seeded`).toBeTruthy();

  await page.goto(`https://trello.com/c/${info.cardShortLink}`);

  const powerUp = page.frameLocator('iframe[src*="trello-excel-preview"]').first();
  const row = powerUp.locator('.attachment-item', { hasText: FIXTURE });
  await row.waitFor({ state: 'visible' });
  await row.locator('.btn-preview').click();

  const previewModal = page.frameLocator('iframe[src*="trello-excel-preview"][src*="preview-html"]');
  const table = previewModal.locator('table').first();
  await expect(table).toBeVisible({ timeout: 15_000 });

  // Wait for xlsx-calc lazy load + computation + default formatting.
  // Expected: "13.00" (10+3) formatted as #,##0.00, not "=A2+B2".
  const sumCell = previewModal.locator('table tr').nth(1).locator('td').nth(2);
  await expect(sumCell).toHaveText('13.00', { timeout: 5_000 });

  // Spot-check the other computed values.
  await expect(previewModal.locator('table tr').nth(2).locator('td').nth(2)).toHaveText('26.00');
  await expect(previewModal.locator('table tr').nth(5).locator('td').nth(2)).toHaveText('65.00');

  expect(cspViolations, cspViolations.join('\n')).toEqual([]);
});
